### ISSUE TITLE
getting issue after successful done meeting

### ISSUE THREAD

**Issue by dipenpatel235** [palexang/bbb-download#3]
Big blue button  version 1

Traceback (most recent call last):
  File "/usr/local/bigbluebutton/core/scripts/post_publish/download.py", line 227, in <module>
    main()
  File "/usr/local/bigbluebutton/core/scripts/post_publish/download.py", line 208, in main
    dictionary, length, dims = prepare()
  File "/usr/local/bigbluebutton/core/scripts/post_publish/download.py", line 157, in prepare
    check_presentation_dims(dictionary, dims)
  File "/usr/local/bigbluebutton/core/scripts/post_publish/download.py", line 123, in check_presentation_dims
    height = max(heights)
ValueError: max() arg is an empty sequence

**Comment by dipenpatel235** [comment]
Hello palexang,
Can You help me to fix out my above issue ?

if you required some more info so let me know...

Thanks

**Comment by alpapado** [comment]
Hi,

Please send the shapes.svg file and the logfile.

**Comment by dipenpatel235** [comment]
Hello...
i am not able to attached .log and .svg file due to github restriction.
That why i have shared dropbox link.

Let me know if you not get below file

LogFile :
https://www.dropbox.com/s/ysy6wuyefy5whgb/4ea6e9874864d2d03a451e963f1c88d615b1bb89-1471696986924.log

Svg file:
https://www.dropbox.com/s/tesfjb1d5u6qnph/shapes.svg

**Comment by dipenpatel235** [comment]
Hello,
Palaxang you got that files ?

**Comment by dipenpatel235** [comment]
Hello Palaxang,
are you busy ?

**Comment by DrydenK** [comment]
[bbb-download-logs.zip](https://github.com/palexang/bbb-download/files/583947/bbb-download-logs.zip)
Hi, I'm getting the same error. I found that it happens when no presentation is uploaded. If only the default presentation is present (The "Welcome to BigBlueButton" one), I get that error. If I upload one presentation, the script moves ahead.

I' running BBB 1.0 in Ubuntu 14.4. Log file and shapes.svg are attached in a zip file.

**Comment by alpapado** [comment]
Sounds like a parsing error. Could you send me also the shapes.svg file
for the case where no presentation is present, as I currently don't have
access to a BBB installation?

**Comment by DrydenK** [comment]
With no pdf at all, the script moved ahead, but failed when concatenating the mp4 files. It failed with the message "[concat @ 0x2d7c3e0] Unsafe file name", on line 157 of the log (attached). This error caused the failure in the funcition  zipdir() at the end.
[bbb-download-logs2.zip](https://github.com/palexang/bbb-download/files/584163/bbb-download-logs2.zip)

**Comment by iluhavlg** [comment]
I got the same problem as @dipenpatel235 if there was no presentation while meeting.
BBB version is 2.0. If I upload presenattion script works well. Log file and shapes.svg file in attach.

[99f3b3ada2b4675c518ff23cbd9539da05e2f1f8-1523521769355.log](https://github.com/alpapado/bbb-download/files/1903466/99f3b3ada2b4675c518ff23cbd9539da05e2f1f8-1523521769355.log)

[shapes.svg.txt](https://github.com/alpapado/bbb-download/files/1903474/shapes.svg.txt)


@alpapado can you help us?
